apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - pvc-daily.yaml
  - pvc-q3.yaml
  - pvc-q6.yaml
  - pvc-q38.yaml
  - router-config.yaml
  - deployment-router.yaml
  - deployment.yaml
  - deployment-q3.yaml
  - deployment-q38.yaml
  - deployment-q6.yaml
  - service-router.yaml
  - service.yaml
  - service-q3.yaml
  - service-q38.yaml
  - service-q6.yaml
  - networkpolicy.yaml
