apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-litellm-ingress
  namespace: llms
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: llama-server
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: litellm
      ports:
        - protocol: TCP
          port: 8080
