apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-models-q6
  namespace: llms
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 35Gi
